files:
  - source: /core/src/main/resources/en_US.yml
    translation: /core/src/main/resources/locales/%locale_with_underscore%.%file_extension%
  - source: /core/src/main/resources/locales/en_US.yml
    translation: /core/src/main/resources/locales/%locale_with_underscore%.%file_extension%
