mysql:
  host: "localhost"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"

default-server-language: 'en_US'

banned-commands-while-mute:
  - command1
  - command2

# NOTE: If you want to use the role cast feature in discord,
# discordsrv's table must be in the same database as this plugin's table.
discord:
  enable: false
  token: 'botToken'
  serverId: 'serverId'
  punish-role:
    enable: false
    punishedRoleId: 'roleId'
  punish-announce:
    enable: false
    channel-id: 'channelId'

debug: false