# This plugin was written by Mehmet_27.
# Its main purpose is to save you from paid plugins.
# If you need help using the plugin, you can reach us here:

mysql:
  enable: false
  host: "localhost"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"

# This will be your server's default language.
# If the player who entered does not have a language file,
# messages in this language will be used.
default-server-language: 'en_US'

# You can enter the names of the players you want to protect from all punish commands.
exempt-players:
  - examplePlayer

# If you turn this on, all player names that have entered the server
# before will also appear in tab completions.
show-all-names-in-tab-completion: true

# Commands you don't want players to use while muted.
banned-commands-while-mute:
  - command1
  - command2

# NOTE: If you want to use the role cast feature in discord,
# discordsrv's table must be in the same database as this plugin's table.
discord:
  enable: false
  token: 'yourBotToken'
  serverId: 'yourServerId'
  punish-role:
    enable: false
    punishedRoleId: 'yourPunishedRoleId'
  punish-announce:
    enable: false
    channel-id: 'yourAnnounceChannelId'
    embeds:
      ban: true
      ipban: true
      kick: true
      mute: true
      tempban: true
      tempmute: true

debug: false