mysql:
  host: "localhost"
  port: "3306"
  database: "database"
  username: "username"
  password: "password"
kick:
  - '&e&lTITTLE'
  - ' '
  - '&6You kicked from this server.'
  - '&2Reason: &a%reason%'