name: Publish to Modrinth
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        cache: 'maven'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml && echo "FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV
    - name: Upload artifact
      uses: RubixDev/modrinth-upload@v1.0.0
      with:
        token: ${{ secrets.MODRINTH_TOKEN }}
        project_id: 2RJlmVr6
        file_path: 'target/${{ env.FINAL_NAME }}.jar'
        changelog: ${{ github.event.release.body }}
        name: ${{ github.event.release.tag_name }}
        version: ${{ github.event.release.tag_name }}
        game_versions: 1.19,1.18,1.17,1.16,1.15,1.14,1.13,1.12,1.11,1.10,1.9,1.8
        release_type: release
        loaders: spigot
        featured: true
